type YamlRecord = Record<string, unknown>;

type RequiredField = { path: string[]; value: string | number | boolean; label: string };
type StackEntry = { indent: number; path: string[] };
type ParsedEntry = { path: string[]; line: number };
type BunYamlRuntime = { YAML?: { parse(source: string): unknown } };

const requiredFields: RequiredField[] = [
  { path: ["version"], value: 14, label: "version" },
  { path: ["policy"], value: "traycer_native_intent_first", label: "policy" },
  { path: ["runtime", "control_plane"], value: "traycer", label: "runtime.control_plane" },
  { path: ["runtime", "harness"], value: "codex", label: "runtime.harness" },
  { path: ["runtime", "fallback_harness"], value: "omp", label: "runtime.fallback_harness" },
  { path: ["runtime", "fallback_mode"], value: "manual_only", label: "runtime.fallback_mode" },
  { path: ["runtime", "daily_entry"], value: "conversation", label: "runtime.daily_entry" },
  { path: ["runtime", "package_extension"], value: "none", label: "runtime.package_extension" },
  { path: ["runtime", "prompts"], value: "none", label: "runtime.prompts" },
  { path: ["runtime", "manager_skills_autoload"], value: false, label: "runtime.manager_skills_autoload" },
  { path: ["execution", "automatic_fallback"], value: false, label: "execution.automatic_fallback" },
  { path: ["execution", "automatic_new_session"], value: false, label: "execution.automatic_new_session" },
  { path: ["execution", "automatic_send"], value: false, label: "execution.automatic_send" },
  { path: ["coordination", "agents"], value: "explicit_user_request_only", label: "coordination.agents" },
  { path: ["approval", "mode"], value: "single_batch_envelope", label: "approval.mode" },
  { path: ["approval", "local_reversible"], value: "proceed", label: "approval.local_reversible" },
];
const piUsagePath = ["runtime", "pi_usage"];
const criticalKeyNames = new Set([...requiredFields.map((field) => field.path.at(-1)), "pi_usage"]);
const criticalPaths = new Set([...requiredFields.map((field) => field.path.join(".")), piUsagePath.join(".")]);
function isRecord(value: unknown): value is YamlRecord { return typeof value === "object" && value !== null && !Array.isArray(value); }
function readPath(document: unknown, path: string[]) { let current = document; for (const key of path) { if (!isRecord(current) || !Object.prototype.hasOwnProperty.call(current, key)) return undefined; current = current[key]; } return current; }
function bunParser() { const bun = (globalThis as typeof globalThis & { Bun?: BunYamlRuntime }).Bun; return bun?.YAML?.parse; }
function grammarError(line: number, reason: string) { return `tool-routing.yaml rejected ${reason} at line ${line} before Bun.YAML.parse`; }
function preflight(policy: string) { const entries: ParsedEntry[] = []; const stack: StackEntry[] = []; const seen = new Map<string, number>(); const errors: string[] = []; const lines = policy.split(/\r?\n/); for (let index = 0; index < lines.length; index += 1) { const line = lines[index]; const lineNumber = index + 1; if (!line.trim()) continue; if (line.includes("\t")) { errors.push(grammarError(lineNumber, "tab indentation")); continue; } const comment = line.match(/^( *)#/); if (comment) { if (comment[1].length % 2 !== 0) errors.push(grammarError(lineNumber, "non-two-space comment indentation")); continue; } if (line.includes("#") || /[{}\[\]|>!&*\\]/.test(line)) { errors.push(grammarError(lineNumber, "unsupported inline comment, flow syntax, tag, anchor, escape, or block scalar")); continue; } const mapping = line.match(/^( *)([A-Za-z_][A-Za-z0-9_-]*):(?:[ ]*([A-Za-z0-9][A-Za-z0-9_.-]*))?[ ]*$/); const list = line.match(/^( *)-[ ]+([A-Za-z0-9][A-Za-z0-9_.-]*)[ ]*$/); if (!mapping && !list) { errors.push(grammarError(lineNumber, "unsupported YAML key or scalar syntax")); continue; } const indent = (mapping ?? list)![1].length; if (indent % 2 !== 0) { errors.push(grammarError(lineNumber, "indentation that is not a multiple of two spaces")); continue; } if (list) { while (stack.length && stack.at(-1)!.indent >= indent) stack.pop(); if (!stack.length) errors.push(grammarError(lineNumber, "list item without a mapping parent")); continue; } while (stack.length && stack.at(-1)!.indent >= indent) stack.pop(); const path = [...(stack.at(-1)?.path ?? []), mapping![2]]; const label = path.join("."); if (seen.has(label)) errors.push(`tool-routing.yaml has duplicate YAML mapping ${label} at lines ${seen.get(label)}, ${lineNumber}`); else seen.set(label, lineNumber); entries.push({ path, line: lineNumber }); if (mapping![3] === undefined) stack.push({ indent, path }); } for (const entry of entries) { const key = entry.path.at(-1); if (key && criticalKeyNames.has(key) && !criticalPaths.has(entry.path.join("."))) { const expected = key === "pi_usage" ? "runtime.pi_usage" : requiredFields.find((field) => field.path.at(-1) === key)?.label ?? key; errors.push(`tool-routing.yaml has ${key} outside ${expected} at ${entry.path.join(".")}`); } } return errors; }
function parsePolicy(policy: string) { const parser = bunParser(); if (!parser) return { document: undefined, errors: ["tool-routing.yaml Bun.YAML.parse is unavailable; refusing to infer policy semantics"] }; try { return { document: parser(policy), errors: [] as string[] }; } catch (error) { const message = error instanceof Error ? error.message : String(error); return { document: undefined, errors: [`tool-routing.yaml YAML parse failed: ${message}`] }; } }
function validateGates(document: unknown) { const value = readPath(document, ["approval", "require_for"]); if (!Array.isArray(value)) return ["tool-routing.yaml approval.require_for must be a block list"]; const gates = new Set(value.filter((entry): entry is string => typeof entry === "string")); const groups = [["installs"], ["credentials", "credentials_or_private_data", "accounts_or_private_data"], ["destructive_actions"], ["commit_or_push", "commits_or_push"], ["deploy_or_production", "vps_or_deploy"], ["external_side_effects"]]; const errors: string[] = []; for (const group of groups) if (!group.some((gate) => gates.has(gate))) errors.push(`tool-routing.yaml approval.require_for missing one of: ${group.join(", ")}`); return errors; }
function validateLocalInvariants(document: unknown) { const section = readPath(document, ["product_integrations"]); const errors: string[] = []; if (!isRecord(section)) return ["tool-routing.yaml missing local product invariant: product_integrations"]; if (readPath(section, ["product_pi_launcher"]) !== "external_desktop_integration") errors.push("tool-routing.yaml product_integrations.product_pi_launcher must be external_desktop_integration"); if (readPath(section, ["agent_runtime"]) !== false) errors.push("tool-routing.yaml product_integrations.agent_runtime must be false"); for (const key of ["ahk_entrypoints", "catalog"]) { const value = readPath(section, [key]); if (!Array.isArray(value) || value.length === 0) errors.push(`tool-routing.yaml product_integrations.${key} must be a non-empty block list`); } if (readPath(section, ["preserve_presets_and_labels"]) !== true) errors.push("tool-routing.yaml product_integrations.preserve_presets_and_labels must be true"); return errors; }
function validatePiUsage(document: unknown) { const value = readPath(document, piUsagePath); const expected = ["product_runtime", "harness_lab"]; if (!Array.isArray(value)) return ["tool-routing.yaml runtime.pi_usage must be a block list under runtime"]; const values = value.map((entry) => String(entry)); const errors: string[] = []; if (values.length !== expected.length || [...values].sort().join("|") !== [...expected].sort().join("|")) errors.push(`tool-routing.yaml runtime.pi_usage must be exactly ${expected.join(" and ")}`); if (new Set(values).size !== values.length) errors.push("tool-routing.yaml runtime.pi_usage contains duplicate entries"); return errors; }
function collectMisplaced(value: unknown, path: string[], errors: string[]) { if (Array.isArray(value)) { value.forEach((item, index) => collectMisplaced(item, [...path, `[${index}]`], errors)); return; } if (!isRecord(value)) return; for (const [key, child] of Object.entries(value)) { const childPath = [...path, key]; if (criticalKeyNames.has(key) && !criticalPaths.has(childPath.join("."))) { const expected = key === "pi_usage" ? "runtime.pi_usage" : requiredFields.find((field) => field.path.at(-1) === key)?.label ?? key; errors.push(`tool-routing.yaml has ${key} outside ${expected} at ${childPath.join(".")}`); } collectMisplaced(child, childPath, errors); } }
function inspect(policy: string) { const grammarErrors = preflight(policy); if (grammarErrors.length) return { document: undefined, errors: [...new Set(grammarErrors)] }; const parsed = parsePolicy(policy); const errors = [...parsed.errors]; if (!parsed.document) return { document: undefined, errors: [...new Set(errors)] }; if (!isRecord(parsed.document)) errors.push("tool-routing.yaml root must be a mapping"); for (const field of requiredFields) { const actual = readPath(parsed.document, field.path); if (actual === undefined) errors.push(`tool-routing.yaml missing ${field.label}; expected ${field.path.at(-1)}: ${String(field.value)}`); else if (typeof actual !== typeof field.value || actual !== field.value) errors.push(`tool-routing.yaml has invalid ${field.label}; expected ${field.path.at(-1)}: ${String(field.value)}`); } errors.push(...validatePiUsage(parsed.document), ...validateGates(parsed.document), ...validateLocalInvariants(parsed.document)); collectMisplaced(parsed.document, [], errors); return { document: parsed.document, errors: [...new Set(errors)] }; }
export function validateToolRoutingPolicy(policy: string) { return inspect(policy).errors; }
export function hasAuthoritativeTraycerEvidence(policy: string) { const result = inspect(policy); return result.errors.length === 0 && readPath(result.document, ["policy"]) === "traycer_native_intent_first" && readPath(result.document, ["runtime", "control_plane"]) === "traycer" && readPath(result.document, ["runtime", "harness"]) === "codex"; }
export function hasStructuredRoutingField(policy: string, path: string[], expected: string | number | boolean) { const result = inspect(policy); return result.errors.length === 0 && readPath(result.document, path) === expected; }
